name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest
        continue-on-error: true

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t cmpfl0w/flask-ci-cd:latest .

      - name: Push Docker Image to DockerHub
        run: docker push cmpfl0w/flask-ci-cd:latest

      - name: Set up Minikube
        run: |
          minikube start
          kubectl cluster-info

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s-deployment.yaml

      - name: Notify Slack on Failure
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' --data \
          '{"text":"🚨 CI/CD Pipeline Failed! Check GitHub Actions for details."}' \
          ${{ secrets.SLACKURL }}
